# fly.toml app configuration file generated for backend-cv on 2025-05-25T11:49:55-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-cv'
primary_region = 'qro'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
